#include<iostream>
#include "line.h"
using namespace std;
int main() {
cout << "Calling all four constructors to make four lines: "<<endl;
Line line1, line2(-1), line3(1,1), line4(-1,-1,-1);
cout << "line1: " << endl;
cout << "\tPoint: (" << line1.GetX() << ", " << line1.GetY() << ")" << endl;
cout << "\tSlope: " << line1.GetSlope() << endl;
cout << "line2: " << endl;
cout << "\tPoint: (" << line2.GetX() << ", " << line2.GetY() << ")" << endl;
cout << "\tSlope: " << line2.GetSlope() << endl;
cout << "line3: " << endl;
cout << "\tPoint: (" << line3.GetX() << ", " << line3.GetY() << ")" << endl;
cout << "\tSlope: " << line3.GetSlope() << endl;
cout << "line4: " << endl;
cout << "\tPoint: (" << line4.GetX() << ", " << line4.GetY() << ")" << endl;
cout << "\tSlope: " << line4.GetSlope() << endl;
cout << "Intersecting the identity with it's orthogonal complement:" << endl;
line1.Intersection(line2);
cout << "Getting an orthogonal line to line 3:" <<endl;
Line line5 = line3.GetPerpendicular();
cout << "line3: ";
line3.PrintSlopeIntercept();
cout << "line4: ";
line5.PrintSlopeIntercept();
cout << "Printing the point slope form of the lines: " << endl;
cout << "Line1: " << endl;
line1.PrintPointSlope();
cout << "Line2: " << endl;
line2.PrintPointSlope();
cout << "Line3: " << endl;
line3.PrintPointSlope();
cout << "Line4: " << endl;
line4.PrintPointSlope();
cout << "Printing the standard form of the lines: " << endl;
cout << "Line1: " << endl;
line1.PrintStandard();
cout << "Line2: " << endl;
line2.PrintStandard();
cout << "Line3: " << endl;
line3.PrintStandard();
cout << "Line4: " << endl;
line4.PrintStandard();
cout << "Printing the slope-intercept form of the lines: " << endl;
cout << "Line1: " << endl;
line1.PrintSlopeIntercept();
cout << "Line2: " << endl;
line2.PrintSlopeIntercept();
cout << "Line3: " << endl;
line3.PrintSlopeIntercept();
cout << "Line4: " << endl;
line4.PrintSlopeIntercept();
cout << "Changing line 4: " << endl;
line4.SetX(-17.3333333333);
line4.SetY(-3.4512345);
line4.SetSlope(1.31124112);
cout << "line4: " << endl;
cout << "\tPoint: (" << line4.GetX() << ", " << line4.GetY() << ")" << endl;
cout << "\tSlope: " << line4.GetSlope() << endl;
line4.PrintPointSlope();
line4.PrintStandard();
line4.PrintSlopeIntercept();
